name: dart_web
description: An absolute bare-bones web app.
# version: 1.0.0
#homepage: https://www.example.com

environment:
  sdk: '>=2.7.0 <3.0.0'

#dependencies:
#  path: ^1.6.0

dev_dependencies:
  http: ^0.12.0+2
  meta: ^1.1.7
  glob: ^1.0.3
  uuid: ^2.0.2
  process_run: ^0.10.3
